
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

tts:
  - platform: google_translate

lovelace:
  mode: yaml

group: !include config/groups/groups.yaml
automation: !include config/automations/automations.yaml
script: !include config/scripts/scripts.yaml
scene: !include config/scenes/scenes.yaml

roku: !include config/components/roku.yaml
sensor: !include config/components/sensors.yaml
      
frontend: !include config/components/frontend.yaml
